version: "3"
services:
    whatsapp-chatgpt:
        container_name: whatsapp-chatgpt
        read_only: false
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            OPENAI_API_KEY: ""
            OPENAI_GPT_MODEL: ""
            PREFIX_ENABLED: "false"
            SERPAPI_API_KEY: ""
        restart: unless-stopped
        volumes:
            - session-data:/app/session
volumes:
    session-data:
